name: we_link_teams
description: Makes use of the agora_rtc_engine plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine:
    # When depending on this package from a real application you should use:
    #   agora_rtc_engine: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  permission_handler: ^6.0.1
  quick_feedback:
  # firebase_core: ^1.3.0
  # cloud_firestore: ^2.3.0


dev_dependencies:
  integration_test: ^1.0.2+2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_native_splash: ^1.2.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splashimage.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
